---
language: ruby
rvm:
- ruby-head
- 2.4.1
- 2.3.4
- 2.2.7
- 2.1.10
- 2.0.0
matrix:
before_install:
- gem install bundler -v 1.13.7
script:
- rake travis
notification:
  email:
  - mrkn@ruby-lang.org
