---
language: ruby
rvm:
- ruby-head
- 2.4.0
- 2.3.3
- 2.2.6
- 2.1.10
- 2.0.0
- 1.9.3
matrix:
  allow_failures:
  - rvm: 1.9.3
before_install:
- gem install bundler -v 1.13.7
script:
- rake travis
notification:
  email:
  - mrkn@ruby-lang.org
